Deal with held messages, deal with empty queue
alexjurkiewicz/apq pull request #2
Opened 2018-05-11 11:57 UTC by bernhardschmidt

Thanks for your work, it is immensely useful. I've added a few small fixes, see below.

2018-05-11 12:02 UTC, alexjurkiewicz commented
Looks great! I've added you as a committer, please feel free to merge this

2019-07-12 16:47 UTC, antoniovl commented
Any plans to merge this PR anytime soon? :-)

2019-07-12 17:52 UTC, bernhardschmidt commented
Hrm, I cannot merge it.

@alexjurkiewicz Could you check the permissions again and/or merge yourself?

2019-07-14 02:08 UTC, alexjurkiewicz requested changes
I've had a bit of time to review this PR. Please have a look and let me know.

BTW, once this PR is merged, I plan to archive this repo, so if you prefer feel free to close this and pre-emptively fork.

2019-07-14 02:08 UTC, alexjurkiewicz commented on apq.py
> +        if line[0] in '0123456789ABCDEF': # XXX: unsure whether long queue IDs also start like that
Is this comment still valid?

2019-07-14 02:08 UTC, alexjurkiewicz commented on apq.py
> +        elif line == 'Mail queue is empty':
This should be part of the test on line 39.

2020-05-22 23:12 UTC, closed without merging